@Library('my-shared-library') _

pipeline{
	agent any
	environment {
		IMAGE = "my-pizza-repo"
	}
	stages{
	    stage('Global Build') {
		steps {
		    smartBuild(imageName: env.IMAGE)
		}
	}
	stage('Kubernetes Deploy') {
           steps {
		sh "kubectl apply -f k8s/deployment.yaml"
		}
	}
  }
}
