// @Library('my-shared-library@main') _

pipeline{
	agent any
	environment {
		IMAGE = "my-pizza-repo"
	}
	stages{
	    stage('Global Build') {
		steps {
		    smartBuild(imageName: env.IMAGE)
		}
	}
	stage('Kubernetes Deploy') {
           steps {
		sh "kubectl apply -f k8s/deployment.yaml"
		}
	}
	stage('Debug Structure') {
	   steps {
		sh "ls -R .."
		}
	}
  
	stage('Debug Library") {
	 steps {
	    script {
		echo "---Listing the files---"
		sh "ls -l ${env.WORKSPACE}@libs/my-shared-library/vars"
		}
	     }
	}
        stage('Global Build') {
	    steps {
		smartBuild(imageName: 'pizza-app')
		}
	    }
      }

}
