apiVersion: apps/v1
kind: Deployment
metadata:
  name: App-Server
spec:
  replication: 2 #run 2 copies for H/A
  selector:
  matchLabels:
    app: App
  template:
    metadata:
      labels:
         app: App
      spec:
        containers:
        - name: App-server
          image: my-pizza-repo:latest
          ports:
            - containerPort: 3000
          env:
          - name: PIZZA_TYPE
            value: "Pepparoni"

